{{- if eq .Values.nginxGateway.kind "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
  {{- with .Values.nginxGateway.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.nginxGateway.replicas }}
  selector:
    matchLabels:
    {{- include "nginx-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "nginx-gateway.selectorLabels" . | nindent 8 }}
      {{- with .Values.nginxGateway.labels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.nginxGateway.podAnnotations .Values.nginxGateway.metrics.enable }}
      annotations:
        {{- if .Values.nginxGateway.podAnnotations }}
        {{- toYaml .Values.nginxGateway.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.nginxGateway.metrics.enable }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.nginxGateway.metrics.port }}"
        {{- if .Values.nginxGateway.metrics.secure }}
        prometheus.io/scheme: "https"
        {{- end }}
        {{- end }}
      {{- end }}
    spec:
      containers:
      - args:
        - controller
        - --gateway-ctlr-name={{ .Values.nginxGateway.gatewayControllerName }}
        - --gatewayclass={{ .Values.nginxGateway.gatewayClassName }}
        - --config={{ include "nginx-gateway.config-name" . }}
        - --service={{ include "nginx-gateway.fullname" . }}
        - --agent-tls-secret={{ .Values.certGenerator.agentTLSSecretName }}
        {{- if .Values.nginx.imagePullSecret }}
        - --nginx-docker-secret={{ .Values.nginx.imagePullSecret }}
        {{- end }}
        {{- if .Values.nginx.imagePullSecrets }}
          {{- range .Values.nginx.imagePullSecrets }}
        - --nginx-docker-secret={{ . }}
          {{- end }}
        {{- end }}
        {{- if .Values.nginx.plus }}
        - --nginx-plus
          {{- if .Values.nginx.usage.secretName }}
        - --usage-report-secret={{ .Values.nginx.usage.secretName }}
          {{- end }}
          {{- if .Values.nginx.usage.endpoint }}
        - --usage-report-endpoint={{ .Values.nginx.usage.endpoint }}
          {{- end }}
          {{- if .Values.nginx.usage.resolver }}
        - --usage-report-resolver={{ .Values.nginx.usage.resolver }}
          {{- end }}
          {{- if .Values.nginx.usage.skipVerify }}
        - --usage-report-skip-verify
          {{- end }}
          {{- if .Values.nginx.usage.caSecretName }}
        - --usage-report-ca-secret={{ .Values.nginx.usage.caSecretName }}
          {{- end }}
          {{- if .Values.nginx.usage.clientSSLSecretName }}
        - --usage-report-client-ssl-secret={{ .Values.nginx.usage.clientSSLSecretName }}
          {{- end }}
        {{- end }}
        {{- if .Values.nginxGateway.metrics.enable }}
        - --metrics-port={{ .Values.nginxGateway.metrics.port }}
        {{- if .Values.nginxGateway.metrics.secure  }}
        - --metrics-secure-serving
        {{- end }}
        {{- else }}
        - --metrics-disable
        {{- end }}
        {{- if .Values.nginxGateway.readinessProbe.enable }}
        - --health-port={{ .Values.nginxGateway.readinessProbe.port }}
        {{- else }}
        - --health-disable
        {{- end }}
        {{- if .Values.nginxGateway.leaderElection.enable }}
        - --leader-election-lock-name={{ include "nginx-gateway.leaderElectionName" . }}
        {{- else }}
        - --leader-election-disable
        {{- end }}
        {{- if not .Values.nginxGateway.productTelemetry.enable }}
        - --product-telemetry-disable
        {{- end }}
        {{- if .Values.nginxGateway.gwAPIExperimentalFeatures.enable }}
        - --gateway-api-experimental-features
        {{- end }}
        {{- if .Values.nginxGateway.snippetsFilters.enable }}
        - --snippets-filters
        {{- end }}
        {{- if .Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
        - --nginx-scc={{ include "nginx-gateway.scc-name" . }}-nginx
        {{- end}}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/instance']
        - name: IMAGE_NAME
          value: {{ .Values.nginxGateway.image.repository }}:{{ default .Chart.AppVersion .Values.nginxGateway.image.tag }}
        image: {{ .Values.nginxGateway.image.repository }}:{{ default .Chart.AppVersion .Values.nginxGateway.image.tag }}
        imagePullPolicy: {{ .Values.nginxGateway.image.pullPolicy }}
        name: nginx-gateway
        {{- if .Values.nginxGateway.lifecycle }}
        lifecycle:
        {{- toYaml .Values.nginxGateway.lifecycle | nindent 10 }}
        {{- end }}
        {{- if .Values.nginxGateway.resources }}
        resources:
        {{- toYaml .Values.nginxGateway.resources | nindent 10 }}
        {{- end }}
        ports:
        - name: agent-grpc
          containerPort: 8443
        {{- if .Values.nginxGateway.metrics.enable }}
        - name: metrics
          containerPort: {{ .Values.nginxGateway.metrics.port }}
        {{- end }}
        {{- if .Values.nginxGateway.readinessProbe.enable }}
        - name: health
          containerPort: {{ .Values.nginxGateway.readinessProbe.port }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: {{ .Values.nginxGateway.readinessProbe.initialDelaySeconds }}
          periodSeconds: 1
        {{- end }}
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 101
          runAsGroup: 1001
        volumeMounts:
        - name: nginx-agent-tls
          mountPath: /var/run/secrets/ngf
        {{- with .Values.nginxGateway.extraVolumeMounts -}}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.nginxGateway.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.nginxGateway.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.nginxGateway.terminationGracePeriodSeconds }}
      {{- if .Values.nginxGateway.affinity }}
      affinity:
      {{- toYaml .Values.nginxGateway.affinity | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nginx-gateway.serviceAccountName" . }}
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      {{- if .Values.nginxGateway.tolerations }}
      tolerations:
      {{- toYaml .Values.nginxGateway.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.nginxGateway.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.nginxGateway.nodeSelector | nindent 8 }}
      {{- end }}
      volumes:
      - name: nginx-agent-tls
        secret:
          secretName: {{ .Values.certGenerator.serverTLSSecretName }}
      {{- with .Values.nginxGateway.extraVolumes -}}
      {{ toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
